language: php

install:
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified' . PHP_EOL; } else { throw new \RuntimeException('Installer corrupt'); }"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - travis_wait php composer.phar install --profile --no-interaction
  - mkdir -p build/logs

php:
  - 7.0
  - nightly

script:
  - ./vendor/bin/phpunit

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry php vendor/bin/codacycoverage clover ./build/logs/clover.xml
